/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.desktop.JPanel;

import com.google.gson.Gson;
import com.mycompany.desktop.API.APIClient;
import com.mycompany.desktop.API.AuthService;
import com.mycompany.desktop.models.Doctor;
import com.mycompany.desktop.utils.SessionManager;
import com.mycompany.desktop.utils.ValidationUtils;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import retrofit2.Call;
import retrofit2.Callback;
import retrofit2.Response;

/**
 *
 * @author admin
 */
public class RegisterDoctorJPanel extends javax.swing.JPanel {

    private AuthService authService;
    private int id_department;

    /**
     * Creates new form RegisterDoctorJPanel
     */
    public RegisterDoctorJPanel(int id_department) {
        initComponents();
        this.id_department = id_department;

        jTextField_bacsi_department_id.setText(id_department + "");
        
        authService = APIClient.getAuthService();
        SessionManager.getInstance().setCurrentUserId(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTextField_bacsi_name = new javax.swing.JTextField();
        jTextField_bacsi_phone = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_bacsi_brithdate = new javax.swing.JTextField();
        jPasswordField_bacsi_pass = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabel_bacsi_loi = new javax.swing.JLabel();
        jTextField_bacsi_email = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton_bacsi_nam = new javax.swing.JRadioButton();
        jRadioButton_bacsi_nu = new javax.swing.JRadioButton();
        jTextField_bacsi_address = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField_bacsi_department_id = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea_bacsi_description = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLable_bacsi_avatar_url = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jTextField_bacsi_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_bacsi_phoneActionPerformed(evt);
            }
        });

        jButton8.setText("Thêm");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Làm mới");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel3.setText("Name");

        jLabel4.setText("Phone");

        jLabel8.setText("BirthDate     YYYY-MM-DD");

        jPasswordField_bacsi_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_bacsi_passActionPerformed(evt);
            }
        });

        jLabel10.setText("Password");

        jTextField_bacsi_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_bacsi_emailActionPerformed(evt);
            }
        });

        jLabel2.setText("Email");

        jRadioButton_bacsi_nam.setText("Male");

        jRadioButton_bacsi_nu.setText("Female");

        jLabel9.setText("Gender");

        jLabel11.setText("Address");

        jLabel12.setText("Description");

        jLabel14.setText("Department_id");

        jTextArea_bacsi_description.setColumns(20);
        jTextArea_bacsi_description.setRows(3);
        jScrollPane4.setViewportView(jTextArea_bacsi_description);

        jLabel13.setText("Avatar_url");

        jLable_bacsi_avatar_url.setText("file");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("NHẬP THÔNG TIN BÁC SĨ:");

        jButton1.setText("Thoát");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel11)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLable_bacsi_avatar_url))
                        .addComponent(jLabel12)
                        .addComponent(jLabel8)
                        .addComponent(jLabel4)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_bacsi_loi)
                        .addComponent(jLabel2)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jButton8)
                            .addGap(18, 18, 18)
                            .addComponent(jButton9)
                            .addGap(18, 18, 18)
                            .addComponent(jButton1))
                        .addComponent(jScrollPane4)
                        .addComponent(jTextField_bacsi_email)
                        .addComponent(jTextField_bacsi_phone)
                        .addComponent(jTextField_bacsi_address)
                        .addComponent(jPasswordField_bacsi_pass)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jTextField_bacsi_brithdate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jRadioButton_bacsi_nam)
                                    .addGap(32, 32, 32)
                                    .addComponent(jRadioButton_bacsi_nu))
                                .addComponent(jLabel9)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jTextField_bacsi_name, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addComponent(jTextField_bacsi_department_id, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(5, 5, 5)
                        .addComponent(jTextField_bacsi_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(4, 4, 4)
                        .addComponent(jTextField_bacsi_department_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_bacsi_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField_bacsi_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_bacsi_brithdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, 0)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton_bacsi_nam)
                            .addComponent(jRadioButton_bacsi_nu))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_bacsi_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLable_bacsi_avatar_url))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(7, 7, 7)
                .addComponent(jPasswordField_bacsi_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_bacsi_loi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButton1))
                .addGap(0, 34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_bacsi_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_bacsi_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_bacsi_phoneActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        clearDoctorUI();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jPasswordField_bacsi_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_bacsi_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_bacsi_passActionPerformed

    private void jTextField_bacsi_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_bacsi_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_bacsi_emailActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        registerDoctor(this.id_department);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    private void clearDoctorUI() {
        jTextField_bacsi_name.setText("");
        jTextField_bacsi_email.setText("");
        jTextField_bacsi_phone.setText("");
        jTextField_bacsi_brithdate.setText("");
        jPasswordField_bacsi_pass.setText("");
        jTextArea_bacsi_description.setText("");
        jTextField_bacsi_address.setText("");
        //jTextField_bacsi_department_id.setText("");
    }

    private Doctor getDoctorFromUI() {
        Doctor doctor = new Doctor();
        char[] passChars = jPasswordField_bacsi_pass.getPassword();
        String password = new String(passChars);

        // Kiểm tra dữ liệu nhập vào
        if (!ValidationUtils.isValidName(jTextField_bacsi_name.getText())) {
            jLabel_bacsi_loi.setText("Please enter your name");
            jTextField_bacsi_name.requestFocus();
            return null;
        }

        if (!ValidationUtils.isValidEmail(jTextField_bacsi_email.getText())) {
            jLabel_bacsi_loi.setText("Please enter a valid email");
            jTextField_bacsi_email.requestFocus();
            return null;
        }

        if (!ValidationUtils.isValidPassword(password)) {
            jLabel_bacsi_loi.setText("Password must be at least 8 characters");
            jPasswordField_bacsi_pass.requestFocus();
            return null;
        }

        if (!jTextField_bacsi_phone.getText().isEmpty() && !ValidationUtils.isValidPhone(jTextField_bacsi_phone.getText())) {
            jLabel_bacsi_loi.setText("Please enter a valid phone number");
            jTextField_bacsi_phone.requestFocus();
            return null;
        }

        doctor.setFull_name(jTextField_bacsi_name.getText().trim());
        doctor.setEmail(jTextField_bacsi_email.getText().trim());
        doctor.setPhone(jTextField_bacsi_phone.getText().trim());
        doctor.setDate_of_birth(jTextField_bacsi_brithdate.getText().trim());

        if (jRadioButton_bacsi_nam.isSelected()) {
            doctor.setGender("Male");
        } else if (jRadioButton_bacsi_nu.isSelected()) {
            doctor.setGender("Female");
        }

        doctor.setPassword(password);
        doctor.setAddress(jTextField_bacsi_address.getText().trim()); // Nếu có trường địa chỉ
        doctor.setDescription(jTextArea_bacsi_description.getText().trim());

        doctor.setAvatar_url(jLable_bacsi_avatar_url.getText().trim());

        try {
            doctor.setDepartment_id(Integer.parseInt(jTextField_bacsi_department_id.getText().trim()));
        } catch (NumberFormatException e) {
            doctor.setDepartment_id(0); // Giá trị mặc định nếu không hợp lệ
        }

        return doctor;
    }

    private void registerDoctor(int id_department) {
        Doctor doctorRequest = getDoctorFromUI();

        if (doctorRequest == null) {
            return;
        }

        // Chuyển đổi birthDate sang Date
        // Tạo request object
        System.out.println("Doctor Data: " + new Gson().toJson(doctorRequest));
        String token = SessionManager.getInstance().getToken();

        authService.registerDoctor(token, doctorRequest).enqueue(new Callback<Doctor>() {
            @Override
            public void onResponse(Call<Doctor> call, Response<Doctor> response) {
                if (response.isSuccessful() && response.body() != null) {
                    JOptionPane.showMessageDialog(null, "Registration successful! Please login.");
                    SwingUtilities.getWindowAncestor(RegisterDoctorJPanel.this).dispose();
                } else {
                    try {
                        String errorMsg = response.errorBody().string();
                        JOptionPane.showMessageDialog(null, "Failed to register!\nError: " + errorMsg);
                    } catch (IOException e) {
                        JOptionPane.showMessageDialog(null, "Failed to read error message!");
                    }
                }
            }

            @Override
            public void onFailure(Call<Doctor> call, Throwable thrwbl) {
                JOptionPane.showMessageDialog(null, "Network error: " + thrwbl.getMessage());

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_bacsi_loi;
    private javax.swing.JLabel jLable_bacsi_avatar_url;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField_bacsi_pass;
    private javax.swing.JRadioButton jRadioButton_bacsi_nam;
    private javax.swing.JRadioButton jRadioButton_bacsi_nu;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea_bacsi_description;
    private javax.swing.JTextField jTextField_bacsi_address;
    private javax.swing.JTextField jTextField_bacsi_brithdate;
    private javax.swing.JTextField jTextField_bacsi_department_id;
    private javax.swing.JTextField jTextField_bacsi_email;
    private javax.swing.JTextField jTextField_bacsi_name;
    private javax.swing.JTextField jTextField_bacsi_phone;
    // End of variables declaration//GEN-END:variables
}
